# Generated by Django 2.1.3 on 2018-11-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Name', max_length=20)),
                ('User_id', models.IntegerField()),
                ('username', models.CharField(help_text='Enter Username', max_length=20)),
                ('password', models.CharField(help_text='Enter Password', max_length=20)),
                ('age', models.IntegerField()),
                ('country', models.CharField(help_text='Enter Country', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Name', max_length=20)),
                ('animal_type', models.CharField(help_text='Enter Animal Type', max_length=20)),
                ('animal_breed', models.CharField(help_text='Enter Breed', max_length=20)),
                ('pid', models.IntegerField()),
                ('vote_count', models.IntegerField()),
                ('age', models.IntegerField()),
                ('picture', models.ImageField(max_length=255, upload_to='')),
                ('pet_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PUPG.Person')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Name', max_length=20)),
                ('User_id', models.IntegerField()),
                ('pet_id', models.IntegerField()),
                ('username', models.CharField(help_text='Enter Username', max_length=20)),
                ('password', models.CharField(help_text='Enter Password', max_length=20)),
                ('age', models.IntegerField()),
                ('country', models.CharField(help_text='Enter Country', max_length=20)),
            ],
        ),
    ]
