# Generated by Django 2.1.3 on 2018-11-07 18:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PUPG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PUPG.Person')),
            ],
        ),
    ]
