# Generated by Django 2.1.3 on 2018-11-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PUPG', '0002_personinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personinstance',
            name='person',
        ),
        migrations.DeleteModel(
            name='PersonInstance',
        ),
    ]
