# Generated by Django 2.1.3 on 2018-11-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PUPG', '0003_auto_20181107_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
