# Generated by Django 2.1.3 on 2018-11-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUPG', '0004_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animal_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird')], help_text='Enter Animal Type', max_length=20),
        ),
    ]
