# Generated by Django 2.1.3 on 2018-11-28 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PUPG', '0006_auto_20181127_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_owner',
        ),
    ]
