# Generated by Django 2.1.3 on 2018-11-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PUPG', '0007_remove_pet_pet_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='picture',
        ),
    ]
