# Generated by Django 2.1.3 on 2018-11-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUPG', '0009_pet_pet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media/', verbose_name='profile picture'),
        ),
    ]
