# Generated by Django 2.1.3 on 2018-11-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PUPG', '0010_pet_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pid',
        ),
    ]
