# Generated by Django 2.1.3 on 2018-11-28 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUPG', '0011_remove_pet_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='animal_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('reptile', 'Reptile'), ('fish', 'Fish'), ('bird', 'Bird'), ('horse', 'Horse'), ('small_mammal', 'Small Mammal'), ('rock', 'Rock'), ('bug', 'Bug')], help_text='Enter Animal Type', max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.ImageField(max_length=255, null=True, upload_to='media/', verbose_name='profile picture'),
        ),
    ]
