# Generated by Django 2.1.3 on 2018-11-28 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PUPG', '0013_auto_20181128_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
